# Generated by Django 4.1.7 on 2023-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_test', '0002_charttest_digit'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
