# Generated by Django 4.1.7 on 2025-12-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_test', '0003_charttest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charttest',
            name='digit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
